### ISSUE TITLE
Add flags and parameters to ctools execution

### ISSUE THREAD

**Issue by toddatctera** [ctera/ctools#17]
It would be nice to be able to call ctools.py or ctools.exe with flags or parameters.

E.g.

`ctools.exe --task 1 --portal todd.portal.com --user todd --password p@ssw0rd`

[argprase](https://docs.python.org/3/library/argparse.html) would be the usual way to do so.

**Comment by toddatctera** [comment]
Reference: https://docs.python.org/3/library/argparse.html

**Comment by toddatctera** [comment]
I've made progress on this. All these arguments worked in the commits in PR #24

```
[todd@toddora-srv ctools]$ python ctools.py -h
usage: ctools.py [-h] [-m] [-rs] [-et] [-es] [-ss] [-us]

Manage CTERA Edge Filers

optional arguments:
  -h, --help            show this help message and exit
  -m, --menu            Show a menu of options to run
  -rs, --get_status     Get and save status of all Filers
  -et, --enable_telnet  Enable telnet on a Filer
  -es, --enable_ssh     Enable ssh on a Filer
  -ss, --suspend_sync   Suspend Sync on a given Filer
  -us, --unsuspend_sync
                        Unsuspend Sync on a given Filer
[todd@toddora-srv ctools]$ 
```
Except `--menu`. I get this traceback

```
[todd@toddora-srv ctools]$ python ctools.py --menu
2021-04-03 00:58:28,632 [INFO] Starting ctools
Traceback (most recent call last):
  File "/home/todd/ctools/ctools.py", line 61, in <module>
    args.action(args)
TypeError: menu() takes 0 positional arguments but 1 was given
```

Which I fixed by changing `def menu()` to `def menu(self` in `menu.py`.

But then, it broke running `python ctools.py` with no arguments to bring up the menu like we had before and I think we should keep if possible to make running it as a binary executable. 

```
[todd@toddora-srv ctools]$ python ctools.py
Traceback (most recent call last):
  File "/home/todd/ctools/ctools.py", line 59, in <module>
    menu()
TypeError: menu() missing 1 required positional argument: 'self'
```

Fortunately, I found a way to fix that too. Just needed to change `ctools.py` to do this is arguments is None.

```
if __name__ == "__main__":
    args = parser.parse_args()
    set_logging(logging.DEBUG)
    if args.action is None:
        self = None
        menu(self)
    logging.info('Starting ctools')
    args.action(args)
    sys.exit('Exiting ctools_arg')

```

Just wanted to note some of the debugging I had done in case I forget why I did some things certain ways.

**Comment by toddatctera** [comment]
@mj-ctera, here's an example running ctools with arguments/parameters instead of using a menu.
Let me know what you think.
It's very nice for testing and I am hopeful we can use this approach to build a GUI with minimal fuss.

You're required to specify a task. You can omit the address, username, or just the password and will be prompted for it if so.

```
todd@laptodd:ctools$ python ctools.py
usage: ctools.py [-h] [-a ADDRESS] [-u USERNAME] [-p PASSWORD]
                 {suspend_sync,unsuspend_sync,get_status,run_cmd,enable_telnet,enable_ssh,disable_ssh}
ctools.py: error: the following arguments are required: task

todd@laptodd:ctools$ python ctools.py unsuspend_sync
Portal (IP, Hostname or FQDN): todd.ctera.me
Admin Username: admin
Admin Password:
2021-04-22 11:06:22,928 [INFO] Starting ctools
2021-04-22 11:06:22,928 [INFO] Logging into todd.ctera.me
2021-04-22 11:06:22,981 [INFO] User logged in. {'host': 'todd.ctera.me', 'user': 'admin'}
2021-04-22 11:06:23,003 [INFO] Successfully logged in to todd.ctera.me
2021-04-22 11:06:23,012 [INFO] Starting unsuspend sync task.
Enter device name: filer1
Enter tenant portal of filer1 : todd
Device found.
2021-04-22 11:06:28,515 [INFO] Unsuspending cloud sync.
2021-04-22 11:06:30,759 [INFO] Unsuspended cloud sync.
Unsuspended sync on filer1
Exiting ctools.

todd@laptodd:ctools$ python ctools.py --address todd.ctera.me --username admin --password p@ssw0rd suspend_sync
2021-04-22 11:07:20,776 [INFO] Starting ctools
2021-04-22 11:07:20,777 [INFO] Logging into todd.ctera.me
2021-04-22 11:07:20,847 [INFO] User logged in. {'host': 'todd.ctera.me', 'user': 'admin'}
2021-04-22 11:07:20,872 [INFO] Successfully logged in to todd.ctera.me
2021-04-22 11:07:20,880 [INFO] Starting suspend sync task.
Enter device name: filer1
Enter tenant portal of filer1 : todd
Device found.
2021-04-22 11:07:26,147 [INFO] Suspending cloud sync.
2021-04-22 11:07:27,245 [INFO] Cloud sync suspended.
Suspended sync on filer1
Exiting ctools.

```
