### ISSUE TITLE
Functions not working against newer sdk version - AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by toddatctera** [ctera/ctools#2]
I get a traceback trying to run the current version of `ctools.py` against the current version of the `ctera-python-sdk`, 2.2.1
This probably worked in an earlier [release](https://github.com/ctera/ctera-python-sdk/releases) but it is not working currently. I was looking through the changes in releases and it seems there have been a few additions to support different gateway/filer authentication methods.

```
todd@desktodd:~/git$ python3 ctools/CTools1.0.py
Portal (IP, Hostname or FQDN): todd.ctera.me
Admin Username: admin
Admin Password:
Output filename. Make sure extension is csv: testy.csv
2020-11-02 14:07:47,671    INFO [login.py:19] [login] - User logged in. {'host': 'todd.ctera.me', 'user': 'admin'}
The file does not exist
Traceback (most recent call last):
  File "ctools/CTools1.0.py", line 86, in <module>
    status()
  File "ctools/CTools1.0.py", line 45, in status
    cloudSyncStatus = filer.get('/proc/cloudsync/serviceStatus')
  File "/home/todd/.local/lib/python3.8/site-packages/cterasdk/client/host.py", line 16, in check_authenticated_and_call
    return function(self, *args, **kwargs)
  File "/home/todd/.local/lib/python3.8/site-packages/cterasdk/client/host.py", line 132, in get
    return self._ctera_client.get(self.base_file_url if use_file_url else self.base_api_url, path, params or {})
  File "/home/todd/.local/lib/python3.8/site-packages/cterasdk/object/Gateway.py", line 136, in base_api_url
    return uri.api(self)
  File "/home/todd/.local/lib/python3.8/site-packages/cterasdk/edge/uri.py", line 19, in api
    return remote(baseurl, base_object_ref.name, device)  # remote, without a Gateway session
AttributeError: 'NoneType' object has no attribute 'name'
```

I think we might need to include the name attribute or something else here when enumerating our filers.
```
filers = global_admin.devices.filers(include=['deviceConnectionStatus.connected', 'deviceReportedStatus.config.hostname'])
```

Because the first trace thrown says "object has no attribute 'name' and name should be returned with the object in line 19 here:
https://github.com/ctera/ctera-python-sdk/blob/2a635d70caa3ce2e2ed33e47ab65e797749398f4/cterasdk/edge/uri.py

**Comment by toddatctera** [comment]
Latest traceback. No change.

```
todd@laptodd:ctools$ ./ctools.py
Available tasks:
    0. Quit ctools
    1. Record status details of all connected Edge Filers.
    2. Enable telnet on one or more connected Edge Filers.

Enter a task number to run: 1
Portal (IP, Hostname or FQDN): todd.ctera.me
Admin Username: admin
Admin Password:
2020-12-29 13:51:41,396    INFO [login.py:18] [login] - Logging into todd.ctera.me
2020-12-29 13:51:41,749    INFO [login.py:19] [login] - User logged in. {'host': 'todd.ctera.me', 'user': 'admin'}
2020-12-29 13:51:41,909    INFO [login.py:21] [login] - Successfully logged in to todd.ctera.me
Enter output filename. Make sure extension is csv: test.csv
Output file does not exist. Creating new file
Traceback (most recent call last):
  File "./ctools.py", line 45, in <module>
    switch()
  File "./ctools.py", line 28, in switch
    tasks.get(option,default)()
  File "/home/todd/git/ctools/status.py", line 40, in status
    cloudSyncStatus = filer.get('/proc/cloudsync/serviceStatus')
  File "/home/todd/.local/lib/python3.6/site-packages/cterasdk/client/host.py", line 16, in check_authenticated_and_call
    return function(self, *args, **kwargs)
  File "/home/todd/.local/lib/python3.6/site-packages/cterasdk/client/host.py", line 132, in get
    return self._ctera_client.get(self.base_file_url if use_file_url else self.base_api_url, path, params or {})
  File "/home/todd/.local/lib/python3.6/site-packages/cterasdk/object/Gateway.py", line 136, in base_api_url
    return uri.api(self)
  File "/home/todd/.local/lib/python3.6/site-packages/cterasdk/edge/uri.py", line 19, in api
    return remote(baseurl, base_object_ref.name, device)  # remote, without a Gateway session
AttributeError: 'NoneType' object has no attribute 'name'
```

The relevant code snippet is:

```
    for tenant in global_admin.portals.tenants():
        global_admin.portals.browse(tenant.name)
        filers = global_admin.devices.filers(include=['deviceConnectionStatus.connected', 'deviceReportedStatus.config.hostname'])
        total_devices = 0
        for filer in filers:
            if filer.deviceConnectionStatus.connected:
                total_devices = total_devices + 1
                cloudSyncStatus = filer.get('/proc/cloudsync/serviceStatus')
```

I think we need to establish a remote session but not sure how.
