### ISSUE TITLE
Task to enable telnet access

### ISSUE THREAD

**Issue by toddatctera** [ctera/ctools#4]
Create an option to enable telnet access. 
I have some working code now but it's very basic and currently doesn't ask the user which filer(s) they want to unlock.
I simply copied @mj-ctera's code from his `status()` function that enumerates all connected filers on each tenant.

Example run:

```
todd@laptodd:ctools$ ./ctools.py
Tasks to run:
    1. Get Details of all Connected Edge Filers to a specific Portal.
    2. Try to enable telnet unlock on every single device.
Enter a task number to execute: 2
Portal (IP, Hostname or FQDN): todd.ctera.me
Admin Username: admin
Admin Password:
2020-12-18 01:01:11,749    INFO [login.py:18] [login] - Logging into todd.ctera.me
2020-12-18 01:01:12, 78    INFO [login.py:19] [login] - User logged in. {'host': 'todd.ctera.me', 'user': 'admin'}
2020-12-18 01:01:12,227    INFO [login.py:21] [login] - Successfully logged in to todd.ctera.me
todd todd-vGateway 6.0.771.19 00:0c:29:18:f3:f7
Enter unlock code: 72b5a79e
2020-12-18 01:01:18,606    INFO [telnet.py:16] [enable] - Enabling telnet access.
2020-12-18 01:01:18,693    INFO [telnet.py:20] [enable] - Telnet access already enabled.
todd@laptodd:ctools$ ./ctools.py
```

Here's the current code I am about to commit

```
unlock.py
version 0.1
from login import login
from cterasdk import *
import logging

def get_info():

    global_admin = login()
    global_admin.portals.browse_global_admin()
    for tenant in global_admin.portals.tenants():
        global_admin.portals.browse(tenant.name)
        filers = global_admin.devices.filers(include=['deviceConnectionStatus.connected'])
        for filer in filers:
            if filer.deviceConnectionStatus.connected:
                device_name = filer.name
                firmware = filer.get('/status/device/runningFirmware')
                mac = filer.get('/status/device/MacAddress')
                print(tenant.name, filer.name, firmware, mac)
                unlock(filer)

def unlock(filer):
    try:
        code = input("Enter unlock code: ")
    except CTERAException as error:
        logging.warning(error)
        print("Something went wrong with the prompt.")
    try:
        filer.telnet.enable(code)
    except CTERAException as error:
        logging.warning(error)
        print("Bad code or something went wrong unlocking device.")
```

**Comment by toddatctera** [comment]
Improvement but still not ideal progress made in commit https://github.com/ctera/ctools/commit/98a2c586e4b0c648a3fb49769e96d102e073f79a

**Comment by toddatctera** [comment]
The next improvement I want to make is to allow us to simply type or select a filer to perform actions on like enable telnet (and in the future get support reports and such). However, I'm not sure how to pass a specific filer or instantiate a filer (or Gateway) object.

Instead of prompting yes/no to unlock each device as the [current code](https://github.com/ctera/ctools/blob/b0f34387b1f623a7fb5236b2533609cbee92668a/unlock.py) does:

With an active, logged in admin object, browsing my tenant portal, I get an attribute error:

```
>>> admin.whoami()
{
     "host": "todd.ctera.me",
     "status": "Active",
     "user": {
          "name": "admin",
          "tenant": "todd",
          "role": "ReadWriteAdmin"
     },
     "local_auth": false,
     "context": "admin"
}
>>> myFiler = admin.devices.device('todd-vGateway')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/todd/.local/lib/python3.6/site-packages/cterasdk/core/devices.py", line 39, in device
    dev = self._portal.get_multi(url, include)
AttributeError: 'str' object has no attribute 'name'
>>>
```

So I'm not sure how, knowing the tenant and device_name, to create a gateway object.

**Comment by ygalblum** [comment]
@toddatctera The same flow works on my setup. Furthermore, I've also tested tried to get a filer that does not exist, and I got a Device Not Found error. 
Did you test it with the latest code?
Can you please paste the entire trace?

**Comment by toddatctera** [comment]
@ygalblum that is the full the trace but here is my whole session from import to trace and then the installed cterasdk 2.7.1

```
[todd@ssh ctools]$ python3
Python 3.6.8 (default, Apr  2 2020, 13:34:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cterasdk import *                                                                                                                                                                                       >>> admin = GlobalAdmin('todd.ctera.me')                                                                                                                                                                         >>> admin.login('admin','<removed>')                                                                                                                                                                        2020-12-30 11:25:44,198    INFO [login.py:19] [login] - User logged in. {'host': 'todd.ctera.me', 'user': 'admin'}
>>> admin.whoami()
{
     "host": "todd.ctera.me",
     "status": "Active",
     "user": {
          "name": "admin",
          "tenant": "todd",
          "role": "ReadWriteAdmin"
     },
     "local_auth": false,
     "context": "admin"
}
>>> myFiler = admin.devices.device('todd-Vgateway')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/todd/.local/lib/python3.6/site-packages/cterasdk/core/devices.py", line 40, in device
    if dev.name is None:
AttributeError: 'str' object has no attribute 'name'
>>>
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
cterasdk (2.7.1)
[todd@ssh ctools]$ python3 -m pip list --user | grep ctera
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
cterasdk (2.7.1)
```

**Comment by toddatctera** [comment]
@ygalblum , appreciate you taking a look and I did provide access to my lab but it seems I can't reproduce anymore despite no changes.

```
[todd@ssh git]$ python3
Python 3.6.8 (default, Apr  2 2020, 13:34:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cterasdk import *                                                                                                                                                                                       >>> admin = GlobalAdmin('todd.ctera.me')                                                                                                                                                                         >>> admin.login('admin','Breakthings456')                                                                                                                                                                        2020-12-30 13:38:10,847    INFO [login.py:19] [login] - User logged in. {'host': 'todd.ctera.me', 'user': 'admin'}
>>> myFiler = admin.devices.device('todd-vGateway')
>>> print(myFiler.n
myFiler.name     myFiler.network  myFiler.nfs      myFiler.ntp
>>> print(myFiler.name)
todd-vGateway
>>>
```

**Comment by toddatctera** [comment]
Added minimum viable prompt to unlock a specific filer in https://github.com/ctera/ctools/commit/b66af9ae0ee0f03042f8a7c409fa03bd6b0749cb
